# Travis configuration
language: python

python:
    - "3.7"
    - "3.8"

matrix:
    include:
        - name: Python 3.7.4 on Windows
          os: windows
          language: shell
          install:
            - choco install python --version 3.7.4
            - pip install -r requirements.txt
            - pip install coveralls
            - python -V
            - pip -V
          env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

        - name: Python 3.8.1 on Windows
          os: windows
          language: shell
          install:
            - choco install python --version 3.8.1
            - pip install -r requirements.txt
            - python -V
            - pip -V
          env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
    - pip install pip --upgrade
    - pip install -r requirements.txt
    - python -V
    - pip -V

script:
    - flake8 --max-line-length=100 --ignore=E402 .
    - pylint --rcfile=pylint.rcfile .
    - bandit -r .
    - radon cc --show-complexity --min B .
    - python visualize.py --no-viewer --initial-cases=4 --format=png --format=svg --country=germany --country=italy --country=france

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
